<a href="https://colab.research.google.com/github/renzojesus25-droid/EDA/blob/main/TrabajoFinal_EDA_PYTHON_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Análisis de Datos Dataset: SUPERSTORE**

*   **Nombres:** Renzo Napan
*   **Módulo:** Introducción a SQL y Python para Análisis de Datos
*   **Fuente del dataset:** Kaggle
*   **Objetivo:** Análisis exploratorio de base de datos de un Supermercado de EEUU usando librerias de Python y consultas en SQL con Duck DB

##Carga del Dataset

In [41]:
import pandas as pd

In [42]:
df = pd.read_csv("/content/Superstore.csv",encoding="latin1")

In [43]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2011-110422,22-01-2011,24-01-2011,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2014-121258,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2014-121258,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2014-121258,27-02-2014,04-03-2014,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2014-119914,05-05-2014,10-05-2014,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

##Exploración Inicial del Dataset

In [44]:
#Tipo de datos por columna
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

## Conversión de tipo de dato para las fechas

In [45]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d-%m-%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d-%m-%Y')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [46]:
#Cantidad de Filas y columnas
df.shape

(9994, 21)

In [47]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [48]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2011-110422,2011-01-22,2011-01-24,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2014-121258,2014-02-27,2014-03-04,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2014-121258,2014-02-27,2014-03-04,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2014-121258,2014-02-27,2014-03-04,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2014-119914,2014-05-05,2014-05-10,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

##Análisis de calidad de datos

In [49]:
#valores nulos por variable
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [50]:
#Se revisaron valores duplicados, no existen duplicados
df.duplicated().sum()

np.int64(0)

##Estadística Descriptiva

In [51]:
#estadísticas descriptivas para variables numéricas
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2013-04-30 19:20:02.401441024,2013-05-04 18:20:49.229537792,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2011-01-04 00:00:00,2011-01-08 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2012-05-23 00:00:00,2012-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2013-06-27 00:00:00,2013-06-30 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2014-05-15 00:00:00,2014-05-19 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2014-12-31 00:00:00,2015-01-06 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [52]:
#Variables categóricas
df.describe(include="object")

,Order ID,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,5009,4,793,793,3,1,531,49,4,1862,3,17,1841
top,CA-2014-100111,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,West,OFF-PA-10001970,Office Supplies,Binders,Staples
freq,14,5968,37,37,5191,9994,915,2001,3203,19,6026,1523,227

In [53]:
df["Category"].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [54]:
df['Sales'].sum()

np.float64(2297200.8603000003)

In [55]:
df['Profit'].sum()

np.float64(286397.0217)

In [56]:
df['Sales'].mean()

np.float64(229.85800083049833)

In [57]:
df['Profit'].sum() / df['Sales'].sum()

np.float64(0.12467217240315603)

In [58]:
df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

In [59]:
df.groupby('City')['Sales'].sum().sort_values(ascending=False)

City
New York City    256368.161
Los Angeles      175851.341
Seattle          119540.742
San Francisco    112669.092
Philadelphia     109077.013
                    ...
Ormond Beach          2.808
Pensacola             2.214
Jupiter               2.064
Elyria                1.824
Abilene               1.392
Name: Sales, Length: 531, dtype: float64

In [60]:
df.groupby('Category')['Profit'].sum().sort_values(ascending=False)

Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

In [61]:
df.groupby('City')['Profit'].sum().sort_values(ascending=False)

City
New York City    62036.9837
Los Angeles      30440.7579
Seattle          29156.0967
San Francisco    17507.3854
Detroit          13181.7908
                    ...
Chicago          -6654.5688
Lancaster        -7239.0684
San Antonio      -7299.0502
Houston         -10153.5485
Philadelphia    -13837.7674
Name: Profit, Length: 531, dtype: float64

| Variable         | Tipo       | ¿Por qué es importante?                                                          |
| ---------------- | ---------- | -------------------------------------------------------------------------------- |
| **Sales**        | Numérica   | Es la principal métrica del negocio. Representa el importe de cada venta.        |
| **Profit**       | Numérica   | Permite medir la rentabilidad de cada transacción y detectar pérdidas.           |
| **Quantity**     | Numérica   | Indica el número de productos vendidos por pedido.                               |
| **Discount**     | Numérica   | Ayuda a analizar el impacto de los descuentos sobre las ventas y las utilidades. |
| **Category**     | Categórica | Permite comparar el desempeño entre categorías de productos.                     |
| **Sub-Category** | Categórica | Ofrece un análisis más detallado dentro de cada categoría.                       |
| **Region**       | Categórica | Facilita el análisis geográfico de las ventas.                                   |
| **Segment**      | Categórica | Permite identificar qué tipo de clientes generan mayores ingresos.               |
| **Order Date**   | Fecha      | Es fundamental para analizar tendencias y evolución de las ventas en el tiempo.  |

##Visualizaciones con Plotly

1. Tendencia de ventas en el tiempo

Permite identificar la evolución de las ventas durante el período analizado y detectar meses con mayor actividad comercial.

In [95]:
# Convertir la fecha
df["Order Date"] = pd.to_datetime(df["Order Date"])

# Agrupar ventas mensuales
ventas_mes = (df.groupby(pd.Grouper(key="Order Date", freq="M"))["Sales"].sum().reset_index())

fig1 = px.line(ventas_mes,x="Order Date",y="Sales",title="Evolución mensual de las ventas",markers=True)

fig1.show()

/tmp/ipykernel_417/3474700328.py:5: FutureWarning:

'M' is deprecated and will be removed in a future version, please use 'ME' instead.

2. Ventas por categoría

Permite comparar cuál categoría genera mayores ingresos.

In [96]:
ventas_categoria = (df.groupby("Category")["Sales"].sum().reset_index())

fig2 = px.bar(ventas_categoria,x="Category",y="Sales", title="Ventas por categoría",text_auto=".2s")

fig2.show()

3. Proporción de ventas por región

Muestra la participación porcentual de cada región dentro del total de ventas.

In [97]:
ventas_region = (df.groupby("Region")["Sales"].sum().reset_index())

fig3 = px.pie(ventas_region,names="Region",values="Sales",title="Participación de ventas por región")

fig3.show()

4. Distribución de las ventas

Permite observar la frecuencia de ventas pequeñas y grandes, así como la concentración de los datos.

In [98]:
fig4 = px.histogram(df,x="Sales",nbins=40,title="Distribución del monto de ventas")

fig4.show()

5. Valores atípicos

Permite identificar ventas excepcionalmente altas o bajas respecto al comportamiento general.

In [99]:
fig5 = px.box(df, y="Sales",title="Valores atípicos en las ventas")

fig5.show()

6. Relación entre ventas y utilidad

Permite analizar si mayores ventas generan necesariamente mayores utilidades.

In [100]:
fig6 = px.scatter(df,x="Sales",y="Profit",color="Category",title="Relación entre ventas y utilidad")

fig6.show()

## Consultas SQL con DuckDB

In [82]:
import duckdb

duckdb.register("superstore", df)

Consulta 1. Ventas totales por categoría

In [84]:
duckdb.sql("""SELECT
    Category,
    ROUND(SUM(Sales),2) AS Total_Ventas
FROM superstore
GROUP BY Category
ORDER BY Total_Ventas DESC;""")

┌─────────────────┬──────────────┐
│    Category     │ Total_Ventas │
│     varchar     │    double    │
├─────────────────┼──────────────┤
│ Technology      │    836154.03 │
│ Furniture       │     741999.8 │
│ Office Supplies │    719047.03 │
└─────────────────┴──────────────┘

Consulta 2. Utilidad promedio por región

In [86]:
duckdb.sql("""SELECT
    Region,
    ROUND(AVG(Profit),2) AS Utilidad_Promedio
FROM superstore
GROUP BY Region
ORDER BY Utilidad_Promedio DESC;""")

┌─────────┬───────────────────┐
│ Region  │ Utilidad_Promedio │
│ varchar │      double       │
├─────────┼───────────────────┤
│ West    │             33.85 │
│ East    │             32.14 │
│ South   │             28.86 │
│ Central │             17.09 │
└─────────┴───────────────────┘

Consulta 3. Top 10 productos con mayores ventas

In [88]:
duckdb.sql("""SELECT
    Product_Name,
    SUM(Sales) AS Ventas
FROM (
    SELECT
        "Product Name" AS Product_Name,
        Sales
    FROM superstore
)
GROUP BY Product_Name
ORDER BY Ventas DESC
LIMIT 10;""")

┌─────────────────────────────────────────────────────────────────────────────┬────────────────────┐
│                                Product_Name                                 │       Ventas       │
│                                   varchar                                   │       double       │
├─────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ Canon imageCLASS 2200 Advanced Copier                                       │          61599.824 │
│ Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind │ 27453.384000000005 │
│ Cisco TelePresence System EX90 Videoconferencing Unit                       │           22638.48 │
│ HON 5400 Series Task Chairs for Big and Tall                                │ 21870.575999999997 │
│ GBC DocuBind TL300 Electric Binding System                                  │          19823.479 │
│ GBC Ibimaster 500 Manual ProClick Binding System                            │            19024.5 │
│ Hewlett Packard LaserJet 3310 Copier                                        │          18839.686 │
│ HP Designjet T520 Inkjet Large Format Printer - 24" Color                   │          18374.895 │
│ GBC DocuBind P400 Electric Binding System                                   │          17965.068 │
│ High Speed Automatic Electric Letter Opener                                 │ 17030.311999999998 │
├─────────────────────────────────────────────────────────────────────────────┴────────────────────┤
│ 10 rows                                                                                2 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

Consulta 4. Ventas por segmento de cliente

In [90]:
duckdb.sql("""SELECT
    Segment,
    COUNT(*) AS Cantidad_Pedidos,
    ROUND(SUM(Sales),2) AS Total_Ventas
FROM superstore
GROUP BY Segment
ORDER BY Total_Ventas DESC;""")

┌─────────────┬──────────────────┬──────────────┐
│   Segment   │ Cantidad_Pedidos │ Total_Ventas │
│   varchar   │      int64       │    double    │
├─────────────┼──────────────────┼──────────────┤
│ Consumer    │             5191 │   1161401.34 │
│ Corporate   │             3020 │    706146.37 │
│ Home Office │             1783 │    429653.15 │
└─────────────┴──────────────────┴──────────────┘

Consulta 5. Estados con mayor utilidad

In [92]:
duckdb.sql("""SELECT
    State,
    ROUND(SUM(Profit),2) AS Utilidad_Total
FROM superstore
GROUP BY State
ORDER BY Utilidad_Total DESC
LIMIT 10;""")

┌────────────┬────────────────┐
│   State    │ Utilidad_Total │
│  varchar   │     double     │
├────────────┼────────────────┤
│ California │       76381.39 │
│ New York   │       74038.55 │
│ Washington │       33402.65 │
│ Michigan   │       24463.19 │
│ Virginia   │       18597.95 │
│ Indiana    │       18382.94 │
│ Georgia    │       16250.04 │
│ Kentucky   │        11199.7 │
│ Minnesota  │       10823.19 │
│ Delaware   │        9977.37 │
├────────────┴────────────────┤
│ 10 rows           2 columns │
└─────────────────────────────┘

Consulta 6. Descuento promedio por categoría

In [94]:
duckdb.sql("""SELECT
    Category,
    ROUND(AVG(Discount),3) AS Descuento_Promedio
FROM superstore
GROUP BY Category;""")

┌─────────────────┬────────────────────┐
│    Category     │ Descuento_Promedio │
│     varchar     │       double       │
├─────────────────┼────────────────────┤
│ Office Supplies │              0.157 │
│ Furniture       │              0.174 │
│ Technology      │              0.132 │
└─────────────────┴────────────────────┘

##**Hallazgos y conclusiones**

**Hallazgos**

*   La categoría Technology concentra el mayor volumen de ventas del negocio.
*   La mayor parte de las transacciones corresponde al segmento Consumer, lo que evidencia que es el principal grupo de clientes.
*   La distribución de las ventas presenta una fuerte asimetría hacia la derecha, indicando que existen muchas ventas de bajo monto y pocas operaciones de alto valor.
*   El diagrama de caja muestra la presencia de valores atípicos, correspondientes a pedidos con importes considerablemente superiores al promedio.
*   La relación entre ventas y utilidad evidencia que no todas las ventas generan la misma rentabilidad, ya que existen operaciones con altos ingresos pero utilidades reducidas, posiblemente debido a descuentos elevados

**Conclusiones**

1.   El análisis exploratorio permitió comprender la estructura y calidad del conjunto de datos antes de realizar análisis más avanzados.
2.   Las visualizaciones interactivas facilitaron la identificación de tendencias, distribuciones y comportamientos relevantes en las ventas.
3. Las consultas SQL mediante DuckDB demostraron que es posible realizar análisis similares a los de una base de datos directamente sobre un DataFrame de pandas.
4. La integración de Python, pandas, Plotly y DuckDB constituye una solución eficiente para el análisis de datos empresariales.
5. Este tipo de análisis proporciona información útil para apoyar la toma de decisiones comerciales, identificar oportunidades de mejora y detectar patrones relevantes en el comportamiento de las ventas.